# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: JPackage

on:
  push:
    tags:
      - 'v*'

jobs:
  jpackage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: JPackage
        run: ./gradlew app:jpackage

      - name: Release-win
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'windows')
        with:
          files: app/build/jpackage/*.msi
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release-mac
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'macos')
        with:
          files: app/build/jpackage/*.dmg
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release-ubuntu
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
        with:
          files: app/build/jpackage/*.rpm
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}